### ISSUE TITLE
Publishing typings

### ISSUE THREAD

**Issue by dinikolop** [flarestart/wait-queue#7]
Hi! I've been using `wait-queue` but currently it is not possible to use class generics (e.g. `new WaitQueue<string>()`). I saw that version 1.1.4 is not yet published in npm.

Is it possible to include a reference to the typing definitions file in package.json so the typings will be accessible, by adding:
```json
 "typings": "dist/index.d.ts",
```
but also update the npm package with the latest changes?
Thanks!

**Comment by flarestart** [comment]
@dinikolop Thanks for the reminder, I have published v1.1.4

**Comment by dinikolop** [comment]
Thank you!
